spring.application.name=backend 
logging.level.root=info
logging.level.htw.gruppe.backend.controller=debug
logging.level.org.hibernate=error


spring.datasource.url=jdbc:postgresql://psql.f4.htw-berlin.de:5432/project25
spring.datasource.username=project25_luise
spring.datasource.password=hQbcFCp5a
spring.sql.init.encoding=UTF-8
spring.sql.init.mode=always

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=mail.htw-berlin.de
spring.mail.port=587
spring.mail.username=fiwproj
spring.mail.password=Folk-Wertlos-Winzig-Tram-Griffel
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.security=DEBUG


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
 

